// Generated by gencpp from file my_kuka_robot/robot_IK.msg
// DO NOT EDIT!


#ifndef MY_KUKA_ROBOT_MESSAGE_ROBOT_IK_H
#define MY_KUKA_ROBOT_MESSAGE_ROBOT_IK_H

#include <ros/service_traits.h>


#include <my_kuka_robot/robot_IKRequest.h>
#include <my_kuka_robot/robot_IKResponse.h>


namespace my_kuka_robot
{

struct robot_IK
{

typedef robot_IKRequest Request;
typedef robot_IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_IK
} // namespace my_kuka_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_kuka_robot::robot_IK > {
  static const char* value()
  {
    return "e2841ca7335735bd34d77773a974ca4b";
  }

  static const char* value(const ::my_kuka_robot::robot_IK&) { return value(); }
};

template<>
struct DataType< ::my_kuka_robot::robot_IK > {
  static const char* value()
  {
    return "my_kuka_robot/robot_IK";
  }

  static const char* value(const ::my_kuka_robot::robot_IK&) { return value(); }
};


// service_traits::MD5Sum< ::my_kuka_robot::robot_IKRequest> should match 
// service_traits::MD5Sum< ::my_kuka_robot::robot_IK > 
template<>
struct MD5Sum< ::my_kuka_robot::robot_IKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_kuka_robot::robot_IK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_IKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_kuka_robot::robot_IKRequest> should match 
// service_traits::DataType< ::my_kuka_robot::robot_IK > 
template<>
struct DataType< ::my_kuka_robot::robot_IKRequest>
{
  static const char* value()
  {
    return DataType< ::my_kuka_robot::robot_IK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_IKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_kuka_robot::robot_IKResponse> should match 
// service_traits::MD5Sum< ::my_kuka_robot::robot_IK > 
template<>
struct MD5Sum< ::my_kuka_robot::robot_IKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_kuka_robot::robot_IK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_IKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_kuka_robot::robot_IKResponse> should match 
// service_traits::DataType< ::my_kuka_robot::robot_IK > 
template<>
struct DataType< ::my_kuka_robot::robot_IKResponse>
{
  static const char* value()
  {
    return DataType< ::my_kuka_robot::robot_IK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_IKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_KUKA_ROBOT_MESSAGE_ROBOT_IK_H
