// Generated by gencpp from file my_kuka_robot/robot_FK.msg
// DO NOT EDIT!


#ifndef MY_KUKA_ROBOT_MESSAGE_ROBOT_FK_H
#define MY_KUKA_ROBOT_MESSAGE_ROBOT_FK_H

#include <ros/service_traits.h>


#include <my_kuka_robot/robot_FKRequest.h>
#include <my_kuka_robot/robot_FKResponse.h>


namespace my_kuka_robot
{

struct robot_FK
{

typedef robot_FKRequest Request;
typedef robot_FKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_FK
} // namespace my_kuka_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_kuka_robot::robot_FK > {
  static const char* value()
  {
    return "5e8f3f69a9d33e59c9acff119ff14aea";
  }

  static const char* value(const ::my_kuka_robot::robot_FK&) { return value(); }
};

template<>
struct DataType< ::my_kuka_robot::robot_FK > {
  static const char* value()
  {
    return "my_kuka_robot/robot_FK";
  }

  static const char* value(const ::my_kuka_robot::robot_FK&) { return value(); }
};


// service_traits::MD5Sum< ::my_kuka_robot::robot_FKRequest> should match 
// service_traits::MD5Sum< ::my_kuka_robot::robot_FK > 
template<>
struct MD5Sum< ::my_kuka_robot::robot_FKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_kuka_robot::robot_FK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_FKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_kuka_robot::robot_FKRequest> should match 
// service_traits::DataType< ::my_kuka_robot::robot_FK > 
template<>
struct DataType< ::my_kuka_robot::robot_FKRequest>
{
  static const char* value()
  {
    return DataType< ::my_kuka_robot::robot_FK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_FKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_kuka_robot::robot_FKResponse> should match 
// service_traits::MD5Sum< ::my_kuka_robot::robot_FK > 
template<>
struct MD5Sum< ::my_kuka_robot::robot_FKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_kuka_robot::robot_FK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_FKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_kuka_robot::robot_FKResponse> should match 
// service_traits::DataType< ::my_kuka_robot::robot_FK > 
template<>
struct DataType< ::my_kuka_robot::robot_FKResponse>
{
  static const char* value()
  {
    return DataType< ::my_kuka_robot::robot_FK >::value();
  }
  static const char* value(const ::my_kuka_robot::robot_FKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_KUKA_ROBOT_MESSAGE_ROBOT_FK_H
