// Generated by gencpp from file my_kuka_robot/robot_IKResponse.msg
// DO NOT EDIT!


#ifndef MY_KUKA_ROBOT_MESSAGE_ROBOT_IKRESPONSE_H
#define MY_KUKA_ROBOT_MESSAGE_ROBOT_IKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace my_kuka_robot
{
template <class ContainerAllocator>
struct robot_IKResponse_
{
  typedef robot_IKResponse_<ContainerAllocator> Type;

  robot_IKResponse_()
    : points()  {
    }
  robot_IKResponse_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;




  typedef boost::shared_ptr< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_IKResponse_

typedef ::my_kuka_robot::robot_IKResponse_<std::allocator<void> > robot_IKResponse;

typedef boost::shared_ptr< ::my_kuka_robot::robot_IKResponse > robot_IKResponsePtr;
typedef boost::shared_ptr< ::my_kuka_robot::robot_IKResponse const> robot_IKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_kuka_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbcffe0108b8e28a6a17e35f91e89d9f";
  }

  static const char* value(const ::my_kuka_robot::robot_IKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbcffe0108b8e28aULL;
  static const uint64_t static_value2 = 0x6a17e35f91e89d9fULL;
};

template<class ContainerAllocator>
struct DataType< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_kuka_robot/robot_IKResponse";
  }

  static const char* value(const ::my_kuka_robot::robot_IKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectoryPoint[] points\n\
\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::my_kuka_robot::robot_IKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_IKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_kuka_robot::robot_IKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_kuka_robot::robot_IKResponse_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_KUKA_ROBOT_MESSAGE_ROBOT_IKRESPONSE_H
